### ISSUE TITLE
Reformat listing elements as an array

### ISSUE THREAD

**Issue by aarjithn** [Bowserinator/Periodic-Table-JSON#13]
I am using this for one of my pet project - and found it would make sense if elements are in an array rather than as properties of the elements object. This makes it easier to loop over and to preserve ordering.

I've got the array version here - https://github.com/aarjithn/Periodic-Table-JSON

Let me know if you like this structure and I can open a PR. Thanks!

**Comment by Bowserinator** [comment]
I guess an array would make more sense for this. Feel free to open a PR.
