### ISSUE TITLE
Why is "number": a string?

### ISSUE THREAD

**Issue by BrandonStaab** [Bowserinator/Periodic-Table-JSON#16]
for example look at Hydrogen:

   {  
      "name": "Hydrogen",
      ...
      "named_by": "Antoine Lavoisier", 
      "number": "1", 
      "period": 1, 
      ...
      "symbol": "H", 
      "xpos": 1, 
      "ypos": 1
   },

**Comment by Bowserinator** [comment]
Fixed.
