### ISSUE TITLE
Not rendered 36 element (Krypton)

### ISSUE THREAD

**Issue by doroninds** [Bowserinator/Periodic-Table-JSON#28]
Hello! I rendering the periodic elements, and 36 element Krypton is not rendered in list.

Example: [Periodic table CSS Grid](https://codepen.io/doroninds/pen/QBEgNQ)

**Comment by Bowserinator** [comment]
This isn't an issue with the JSON file. The krypton description text contains quotes so your HTML in the div got messed up and thus it didn't display
```html
<div class="element noble gas" title="Krypton (from Greek:κρυπτός kryptos " the="" hidden="" one")="" is="" a="" chemical="" element="" with="" symbol="" kr="" and="" atomic="" number="" 36.="" it="" member="" of="" group="" 18="" (noble="" gases)="" elements.="" colorless,="" odorless,="" tasteless="" noble="" gas,="" krypton="" occurs="" in="" trace="" amounts="" atmosphere,="" isolated="" by="" fractionally="" distilling="" liquefied="" air,="" often="" used="" other="" rare="" gases="" fluorescent="" lamps."="">
<span class="element__number">36</span>
<span class="element__symbol">Kr</span>
<span class="element__name">Krypton</span>
<span class="element__atomic_mass">83.80</span>
</div>
```
*As you can see above*

The solution would be to escape the description text before adding it as a string. Also btw did you know each element has a grid position property in the JSON? The `x_pos` and `y_pos` properties give the grid coordinates, where 1,1 is the top left corner.

**Comment by doroninds** [comment]
Thanks for solution!
