### ISSUE TITLE
Created package based on your work

### ISSUE THREAD

**Issue by SwitchCat** [Bowserinator/Periodic-Table-JSON#39]
[switchcat/periodic](https://packagist.org/packages/switchcat/periodic)

**Comment by Bowserinator** [comment]
Cool, glad to see people are using this :D

You may need to include the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) since some of the summaries are ripped from Wikipedia, but other than that it looks good.

**Comment by SwitchCat** [comment]
Indeed, it is now corrected.
