### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by AlixANNERAUD** [Bowserinator/Periodic-Table-JSON#40]
Have you planned to add color later or you will let the color label empty ? Because if it is the case, you can remove it, it is useless and lead to confusion.
Thank you for your work !

**Comment by cdstanford** [comment]
@linares-m I think that would be a good change. I suggest just removing the color field. The only element that has a color listed is Cobalt and that can be part of the "appearance" instead

**Comment by Bowserinator** [comment]
Color field has been removed :)

It was from when I first made this many years ago and I never bothered to remove it till now.
