### ISSUE TITLE
Missing isotopes data

### ISSUE THREAD

**Issue by moazzam125** [Bowserinator/Periodic-Table-JSON#44]
Greetings!
    I found that 'isotopes data' is missing in this pt-json repo. Is there anyone available on **web** OR **suggest me a structure** to be added in the repo.

Here I found some isotope raw data https://periodictable.com/Properties/A/KnownIsotopes.html

**Comment by Bowserinator** [comment]
Maybe something like:
```js
"hydrogen": {
   "isotopes": [1,2,3,4,5,6,7]
   ...
}
```

**Comment by moazzam125** [comment]
Thanks for reponse, I will arrange that this month and pull request.

**Comment by pendragons-code** [comment]
So what happened to this?

**Comment by moazzam125** [comment]
Sorry to say, but I have closed my project in which "isotopes data is required" so there's no need anymore.
