### ISSUE TITLE
Shouldn't it be "caesium" instead of "cesium"?

### ISSUE THREAD

**Issue by Juhan280** [Bowserinator/Periodic-Table-JSON#45]
https://github.com/Bowserinator/Periodic-Table-JSON/blob/b1fece0a0e66bfc4f5532315e950f63ce24c8493/periodic-table-lookup.json#L2584

**Comment by Bowserinator** [comment]
Depends on preference, in American english it's cesium.

**Comment by Bowserinator** [comment]
Yeah.. I'm not sure if I should change it now, because caesium is more common, but it might break existing scripts using the JSON. Do you have any suggestions?
