### ISSUE TITLE
Information on valency?

### ISSUE THREAD

**Issue by PrateekPathak9002** [Bowserinator/Periodic-Table-JSON#46]
There's no information on the valency of the elements. Valency would be really useful.

**Comment by OneByteGH** [comment]
Will add these soon

**Comment by pendragons-code** [comment]
> Will add these soon

is this issue resolved yet?

**Comment by OneByteGH** [comment]
Do you know any online lists that have valencies of all elements? I can scrape them and add to the json @pendragons-code

**Comment by pendragons-code** [comment]
I mean if we can't, just find the proton number, check for the sum, if it
is less than 10, we subtract 2. And we just apply it like that. If the
value is like 20, -2 -8 -8, we would get the valence (i mean this is
valence). I decided to do this for my projrct in the end.

**Comment by OneByteGH** [comment]
Ill use that to add it to the script

**Comment by pendragons-code** [comment]
> Ill use that to add it to the script

I might do it for the author and make a PR, see how my exams goes :]

**Comment by pendragons-code** [comment]
> Ill use that to add it to the script

https://en.wikipedia.org/wiki/List_of_elements_by_atomic_properties
Yo my mate.

**Comment by pendragons-code** [comment]
> There's no information on the valency of the elements. Valency would be really useful.

i mean if the group number is there it is basically the valence

**Comment by pendragons-code** [comment]
taking a closer look, each element has a shell object, just take the last number in the array.

**Comment by PrateekPathak9002** [comment]
Yeah I got it.
