### ISSUE TITLE
Fermium information not showing

### ISSUE THREAD

**Issue by PrateekPathak9002** [Bowserinator/Periodic-Table-JSON#47]
I am making a periodic table game which uses your json. I need to render the information for every element dynamically. I got the info using ajax. The info comes for all the elements except a few. I have found fermium to be one of them. Here is what pops up:
Working element:
![image](https://user-images.githubusercontent.com/89402723/151701257-7f93b942-d7eb-49f5-ad54-6dcee19f42cb.png)
Fermium on the same page:
![image](https://user-images.githubusercontent.com/89402723/151701275-399e8805-b095-4a8c-b7f1-552906e99dbe.png)
I have made one observation. If I wait for 2 minutes, then the info comes. Without reload. At that time though, all the info has loaded. Why is it happening and how can I fix it?

**Comment by Bowserinator** [comment]
This seems to be an issue with your code and not with the JSON. 

Maybe check if there are any nulls that you aren't handling, or any characters you aren't properly escaping?

**Comment by PrateekPathak9002** [comment]
Ok, I'll check it. Thanks!
