### ISSUE TITLE
Source of information

### ISSUE THREAD

**Issue by szepeviktor** [Bowserinator/Periodic-Table-JSON#60]
Hello! What is source of basic information of elements?

Thank you.

**Comment by Bowserinator** [comment]
Wikipedia

**Comment by szepeviktor** [comment]
Oh nooo! 🙃 

I thought something like https://github.com/IUPAC

Thank you for your answer.

**Comment by szepeviktor** [comment]
My thinking is that 6k lines of data must have errors.
