### ISSUE TITLE
Reflow Configuration Question

### ISSUE THREAD

**Issue by jmegginson** [Bowserinator/Periodic-Table-JSON#66]
Is there a configuration or setting to keep the periodic table from reflowing? In other words, is there a way to retain the the whole (default 18-column) periodic table layout regardless of breakpoints/viewport size?  We're aware that horizontal scrolling could ensue but we're wondering if there is an option none the less.

**Comment by Bowserinator** [comment]
Are you sure this is the right repo? This is the repo for the periodic table JSON, not a website.

**Comment by jmegginson** [comment]
Wrong repo. Apologies. Thank you.
