### ISSUE TITLE
Re-order JSON

### ISSUE THREAD

**Issue by PeterBeard** [Bowserinator/Periodic-Table-JSON#8]
@wolfy1339 mentioned ordering the elements by atomic number and I think this is a good idea. It would also probably be smart to organize the fields in some way, probably alphabetically? I'm thinking something like this would be good:

```
"Lead":{
  "appearance":"metallic gray",
  "atomic_mass":207.21,
  "boil":2022
  "category":"post-transition metal",
  "color":null,
  "density":11.34,
  "discovered_by":"Middle East",
  "melt":600.61,
  "molar_heat":26.65,
  "named_by":null,
  "number":"82",
  "period":6,
  "phase":"Solid",
  "source":"https://en.wikipedia.org/wiki/Lead_(element)",
  "spectral_img":null,
  "summary":"Lead (/l\u025bd/) is a chemical element in the carbon group with symbol Pb (from Latin:plumbum) and atomic number 82. Lead is a soft, malleable and heavy post-transition metal. Metallic lead has a bluish-white color after being freshly cut, but it soon tarnishes to a dull grayish color when exposed to air.",
  "symbol":"Pb",
  "xpos":14,
  "ypos":6
},
```

That would make it easier to add fields without things moving around too much. I'm willing to re-organize things but I'll only open a PR if @Bowserinator thinks its worth doing.

**Comment by wolfy1339** [comment]
@PeterBeard go ahead, I talked to @Bowserinator

**Comment by Bowserinator** [comment]
Alright think I fixed it, thanks for your suggestions and PRs!
